### ISSUE TITLE
WIFI Switch for HA

### ISSUE THREAD

**Issue by mukundv** [rytilahti/python-mirobo#12]
Not really an issue, but apparently the wifi switch operates exactly like the vacuum. Do you have any idea how to get this working. When i run this on HA (with all the dependencies), i get the token back with `mirobo discover`. However, the HA component times out.
My HA config is as below
```
switch:
   - platform: mirobo
     name: 'Xiaomi Socket'
     host: host
     token:  'token'
```
Any ideas, help is appreciated.

Thanks
